export const s: Record<string, React.CSSProperties> = {
  page: { padding: "24px", maxWidth: "1100px", margin: "0 auto" },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "24px",
  },
  title: { fontSize: "22px", fontWeight: 600, margin: 0 },
  subtitle: { fontSize: "16px", fontWeight: 500, marginBottom: "16px" },
  card: {
    background: "#fff",
    borderRadius: "10px",
    boxShadow: "0 1px 4px rgba(0,0,0,0.08)",
    padding: "24px",
    marginBottom: "20px",
  },
  grid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "14px" },
  row: {
    display: "flex",
    gap: "8px",
    marginTop: "16px",
    justifyContent: "end",
  },
  label: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    fontSize: "13px",
    fontWeight: 500,
  },
  input: {
    border: "1px solid #cbd5e1",
    borderRadius: "6px",
    padding: "7px 10px",
    fontSize: "14px",
  },
  btnPrimary: {
    background: "var(--primary)",
    color: "var(--white)",
    border: "none",
    borderRadius: "var(--radius-sm)",
    padding: "10px 20px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: 600,
  },
  btnSecondary: {
    background: "#f1f5f9",
    color: "#333",
    border: "1px solid #cbd5e1",
    borderRadius: "6px",
    padding: "8px 16px",
    cursor: "pointer",
    fontSize: "14px",
  },
  btnEdit: {
    background: "#f59e0b",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    padding: "4px 10px",
    cursor: "pointer",
    fontSize: "13px",
    marginRight: "6px",
  },
  btnDelete: {
    background: "#ef4444",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    padding: "4px 10px",
    cursor: "pointer",
    fontSize: "13px",
  },
  activo: {
    background: "#dcfce7",
    color: "#166534",
    borderRadius: "999px",
    padding: "2px 10px",
    fontSize: "12px",
  },
  inactivo: {
    background: "#fee2e2",
    color: "#991b1b",
    borderRadius: "999px",
    padding: "2px 10px",
    fontSize: "12px",
  },
  btnIcon: {
    background: "var(--neutral)",
    border: "none",
    borderRadius: "var(--radius-sm)",
    padding: "6px 8px",
    cursor: "pointer",
    fontSize: "14px",
  },
  btnHelp: {
    background: "#fff",
    color: "#2D6A4F",
    border: "1.5px solid #2D6A4F",
    borderRadius: "var(--radius-sm)",
    padding: "8px 16px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: 600,
  },
};
