import type { CSSProperties } from "react";

export const crudStyles: Record<string, CSSProperties> = {
  shell: {
    minHeight: "100svh",
    background: "var(--bg)",
    color: "var(--text)",
    textAlign: "left",
  },
  shellInner: {
    maxWidth: "1100px",
    margin: "0 auto",
    padding: "24px",
    boxSizing: "border-box",
  },
  nav: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    padding: "20px 24px",
    borderBottom: "1px solid var(--border)",
    position: "sticky",
    top: 0,
    background: "var(--bg)",
    zIndex: 20,
  },
  navLink: {
    textDecoration: "none",
    padding: "9px 14px",
    borderRadius: "999px",
    border: "1px solid var(--border)",
    color: "var(--text-h)",
    fontSize: "14px",
    fontWeight: 500,
  },
  navLinkActive: {
    background: "var(--accent-bg)",
    border: "1px solid var(--accent-border)",
    color: "var(--accent)",
  },
  page: { maxWidth: "1100px", margin: "0 auto" },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "16px",
    marginBottom: "24px",
    flexWrap: "wrap",
  },
  titleGroup: { display: "flex", flexDirection: "column", gap: "6px" },
  title: { fontSize: "22px", fontWeight: 600, margin: 0, color: "var(--text-h)" },
  subtitle: { fontSize: "16px", fontWeight: 500, marginBottom: "16px", color: "var(--text-h)" },
  description: { margin: 0, fontSize: "14px", color: "var(--text)" },
  card: {
    background: "var(--bg)",
    borderRadius: "12px",
    border: "1px solid var(--border)",
    boxShadow: "var(--shadow)",
    padding: "24px",
    marginBottom: "20px",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "14px",
  },
  row: { display: "flex", gap: "8px", marginTop: "16px", flexWrap: "wrap" },
  label: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    fontSize: "13px",
    fontWeight: 500,
    color: "var(--text-h)",
  },
  input: {
    border: "1px solid var(--border)",
    borderRadius: "8px",
    padding: "10px 12px",
    fontSize: "14px",
    background: "transparent",
    color: "var(--text-h)",
  },
  inputReadonly: {
    border: "1px solid var(--border)",
    borderRadius: "8px",
    padding: "10px 12px",
    fontSize: "14px",
    background: "var(--code-bg)",
    color: "var(--text)",
  },
  tableWrap: { overflowX: "auto" },
  table: { width: "100%", borderCollapse: "collapse", fontSize: "14px" },
  thead: { background: "var(--code-bg)" },
  th: {
    padding: "12px 14px",
    textAlign: "left",
    fontWeight: 600,
    borderBottom: "1px solid var(--border)",
    color: "var(--text-h)",
    whiteSpace: "nowrap",
  },
  tr: { borderBottom: "1px solid var(--border)" },
  td: { padding: "12px 14px", verticalAlign: "top" },
  empty: { textAlign: "center", padding: "32px", color: "var(--text)" },
  btnPrimary: {
    background: "var(--accent)",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    padding: "10px 16px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: 600,
  },
  btnSecondary: {
    background: "transparent",
    color: "var(--text-h)",
    border: "1px solid var(--border)",
    borderRadius: "8px",
    padding: "10px 16px",
    cursor: "pointer",
    fontSize: "14px",
  },
  btnEdit: {
    background: "#f59e0b",
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    padding: "6px 10px",
    cursor: "pointer",
    fontSize: "13px",
    marginRight: "6px",
  },
  btnDelete: {
    background: "#ef4444",
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    padding: "6px 10px",
    cursor: "pointer",
    fontSize: "13px",
  },
  activo: {
    background: "#dcfce7",
    color: "#166534",
    borderRadius: "999px",
    padding: "3px 10px",
    fontSize: "12px",
    fontWeight: 600,
    display: "inline-flex",
  },
  inactivo: {
    background: "#fee2e2",
    color: "#991b1b",
    borderRadius: "999px",
    padding: "3px 10px",
    fontSize: "12px",
    fontWeight: 600,
    display: "inline-flex",
  },
  info: {
    background: "var(--code-bg)",
    border: "1px solid var(--border)",
    borderRadius: "10px",
    padding: "12px 14px",
    fontSize: "13px",
    color: "var(--text)",
  },
  error: {
    background: "rgba(239,68,68,0.12)",
    color: "#b91c1c",
    border: "1px solid rgba(239,68,68,0.28)",
    borderRadius: "10px",
    padding: "12px 14px",
    marginBottom: "16px",
    fontSize: "14px",
  },
  statGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "14px",
    marginBottom: "20px",
  },
  statCard: {
    background: "var(--bg)",
    border: "1px solid var(--border)",
    borderRadius: "12px",
    padding: "18px",
    boxShadow: "var(--shadow)",
  },
  statLabel: { fontSize: "13px", color: "var(--text)", marginBottom: "6px" },
  statValue: { fontSize: "28px", fontWeight: 700, color: "var(--text-h)" },
  actionCell: { whiteSpace: "nowrap" },
};
