export const s: Record<string, React.CSSProperties> = {
  page: { padding: "24px", maxWidth: "1100px", margin: "0 auto" },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "24px",
  },
  title: { fontSize: "22px", fontWeight: 600, margin: 0 },
  subtitle: { fontSize: "16px", fontWeight: 500, marginBottom: "16px" },
  card: {
    background: "#fff",
    borderRadius: "10px",
    boxShadow: "0 1px 4px rgba(0,0,0,0.08)",
    padding: "24px",
    marginBottom: "20px",
  },
  grid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "14px" },
  row: { display: "flex", gap: "8px", marginTop: "16px" },
  label: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    fontSize: "13px",
    fontWeight: 500,
  },
  input: {
    border: "1px solid #cbd5e1",
    borderRadius: "6px",
    padding: "7px 10px",
    fontSize: "14px",
    fontFamily: "inherit",
  },
  inputReadonly: {
    border: "1px solid #e2e8f0",
    borderRadius: "6px",
    padding: "7px 10px",
    fontSize: "14px",
    fontFamily: "inherit",
    background: "#f8fafc",
    color: "#64748b",
  },
  btnPrimary: {
    background: "var(--primary)",
    color: "var(--white)",
    border: "none",
    borderRadius: "6px",
    padding: "8px 16px",
    cursor: "pointer",
    fontSize: "14px",
  },
  btnSecondary: {
    background: "#f1f5f9",
    color: "#333",
    border: "1px solid #cbd5e1",
    borderRadius: "6px",
    padding: "8px 16px",
    cursor: "pointer",
    fontSize: "14px",
  },
  btnHelp: {
    background: "#fff",
    color: "#2D6A4F",
    border: "1.5px solid #2D6A4F",
    borderRadius: "6px",
    padding: "8px 16px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: 600,
  },
  btnIcon: {
    background: "#f1f5f9",
    border: "none",
    borderRadius: "6px",
    padding: "6px 8px",
    cursor: "pointer",
    fontSize: "14px",
    marginRight: "4px",
  },
  btnEjecutar: {
    background: "#16a34a",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    padding: "4px 10px",
    cursor: "pointer",
    fontSize: "12px",
    marginRight: "4px",
    fontWeight: 500,
  },
  btnRechazar: {
    background: "#ef4444",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    padding: "4px 10px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 500,
  },
  error: {
    background: "#fef2f2",
    border: "1px solid #fecaca",
    color: "#dc2626",
    borderRadius: "6px",
    padding: "10px 14px",
    fontSize: "13px",
    marginBottom: "12px",
  },
  // Status badges
  badgePendiente: {
    background: "#fef3c7",
    color: "#92400e",
    borderRadius: "999px",
    padding: "2px 10px",
    fontSize: "12px",
  },
  badgeEnRevision: {
    background: "#dbeafe",
    color: "#1e40af",
    borderRadius: "999px",
    padding: "2px 10px",
    fontSize: "12px",
  },
  badgeProcesando: {
    background: "#ede9fe",
    color: "#5b21b6",
    borderRadius: "999px",
    padding: "2px 10px",
    fontSize: "12px",
  },
  activo: {
    background: "#dcfce7",
    color: "#166534",
    borderRadius: "999px",
    padding: "2px 10px",
    fontSize: "12px",
  },
  inactivo: {
    background: "#fee2e2",
    color: "#991b1b",
    borderRadius: "999px",
    padding: "2px 10px",
    fontSize: "12px",
  },
  badgeGris: {
    background: "#f1f5f9",
    color: "#475569",
    borderRadius: "999px",
    padding: "2px 10px",
    fontSize: "12px",
  },
  previewBox: {
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    borderRadius: "8px",
    padding: "14px",
    marginTop: "12px",
    marginBottom: "4px",
  },
  previewHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "10px",
  },
  previewTitle: {
    fontSize: "13px",
    fontWeight: 600,
    color: "#334155",
  },
  previewMonto: {
    fontSize: "13px",
    color: "#475569",
  },
  previewTable: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: "13px",
  },
  previewTh: {
    textAlign: "left" as const,
    padding: "6px 8px",
    borderBottom: "1px solid #e2e8f0",
    color: "#64748b",
    fontWeight: 500,
  },
  previewTd: {
    padding: "6px 8px",
    borderBottom: "1px solid #f1f5f9",
    color: "#1e293b",
  },
};
